### ISSUE TITLE
Black screen when there is an incoming call if the proximity sensor is covered by something.

### ISSUE THREAD

**Issue by PaPa1ya** [a-huk/otaserver#3]
Version 20210623, OrangeFox recovery. Clean installation, in addition only magisk is installed. Changing "Prevent accidental wake-up" does not help.

**Comment by a-huk** [comment]
Please use the forum for this https://forum.xda-developers.com/t/rom-unofficial-11-0-lineage-os-18-1-xiaomi-a2-lite.4229439/ in the future.
I'll have a look, but it is hard to do anything without a log. Are you sure you did not change your screen as there might be glue or dust in front of the sensors.

**Comment by PaPa1ya** [comment]
I tried clearing the default data and cache of the dialer app, but that didn't help. I installed another app and installed it by default (Simple Dialer). That helped. 
To repeat this error, you just need to put your hand to the proximity sensor and call at that point.
