### ISSUE TITLE
random(and not) reboots

### ISSUE THREAD

**Issue by 0ldude-zz** [a-huk/otaserver#4]
Xda is now crippled with anti-features so I'll report here.
With the latest ota(May 24) this has been slightly reduced.
I get random reboots about twice a day, and not-so-random 
reboots when i turn off and on  "Mobile data".
Device doesn't get hot and it doesn't always happen when it's under 
heavy use.
I'll be happy to help identify the issue, 
let me know how.
Keep up the good work :)

**Comment by a-huk** [comment]
Provide logs, and please post it on XDA
