### ISSUE TITLE
Upload microG release

### ISSUE THREAD

**Issue by julianfairfax** [a-huk/otaserver#5]
As discussed in #2, a microG version would be nice. One was released but the link no longer works. I tested it and it works perfectly fine. I understand no future builds have been released but it would at least be nice if that build could be added to https://github.com/a-huk/otaserver/releases so we can download it. Thanks for making this ROM!

**Comment by julianfairfax** [comment]
I uploaded it here in case anyone wants it: https://github.com/julianfairfax/otaserver/releases/tag/17 It's tagged and named in accordance with it's closest released version of the regular build.

**Comment by julianfairfax** [comment]
Closing since i no longer have the device so I can't test

**Comment by a-huk** [comment]
Sorry to hear that. I know have the sufficient space to build both versions, expect them to come soon.
